CREATE DATABASE "project-sem-1";

\c "project-sem-1";

CREATE TABLE IF NOT EXISTS prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name text,
  category text,
  price int,
  create_date date
);

